version: '3.2'
services:
  travis_db:
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: kekko
    networks:
      - dbnet
    ports:
      - "5432:5432"
networks:
  dbnet:
    driver: bridge